// <auto-generated />
namespace IpWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig26Alon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig26Alon));
        
        string IMigrationMetadata.Id
        {
            get { return "202106302342316_mig26Alon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
